version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: greenhouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # ASP-NET reads “ConnectionStrings:DefaultConnection” exactly like this:
      ConnectionStrings__DefaultConnection: |
        Host=db;Port=5432;Database=greenhouse;Username=postgres;Password=postgres
      JWT__ValidIssuer:   GreenhouseApi
      JWT__ValidAudience: GreenhouseApiUsers
      JWT__Secret:        CHANGE_ME_FOR_PROD
    # optional: make sure EF Core finishes its first migration after DB is ready
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      retries: 10
      start_period: 20s

volumes:
  pgdata:
