version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: greenhouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # same as ASPNETCORE_URLS in the Dockerfile, but here you can override if you want
      ASPNETCORE_URLS: http://+:8080

      # connection string for EF Core / DbContext
      ConnectionStrings__DefaultConnection: >
        Host=db;Port=5432;Database=greenhouse;Username=postgres;Password=postgres

      # JWT configuration
      JWT__ValidIssuer:   GreenhouseApi
      JWT__ValidAudience: GreenhouseApiUsers
      JWT__Secret:        CHANGE_ME_FOR_PROD

      # worker seed account pulled by your DbSeeder
      WorkerCredentials__Username: ml-worker
      WorkerCredentials__Password: Super!Secure!PW

volumes:
  pgdata:
