version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: greenhouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: |
        Host=db;Port=5432;Database=greenhouse;Username=postgres;Password=postgres
      JWT__ValidIssuer:   GreenhouseApi
      JWT__ValidAudience: GreenhouseApiUsers
      JWT__Secret:        CHANGE_ME_FOR_PROD
      # worker seed account (pulled by DbSeeder)
      WorkerCredentials__Username: ml-worker
      WorkerCredentials__Password: Super!Secure!PW
